require:
  - rubocop-performance

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - webmention.gemspec
    - test/**/*

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - test/**/*

Style/SymbolArray:
  Enabled: false
