require:
  - rubocop-performance

Layout/AlignHash:
  EnforcedColonStyle: table

Metrics/BlockLength:
  Exclude:
    - test/**/*

Metrics/LineLength:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - test/**/*
