Layout/EmptyLineBetweenDefs:
  Exclude:
    - test/**/parser_test.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - test/**/*
